"use client";

import { useState, useEffect } from "react";
import { TextComponent } from "@/components/Workflow";
import { Heading } from "@/components/heading";
import { Subheading } from "@/components/subheading";
import { cn } from "@/utils/util";

const data = [
  {
    title: "Configure strategy parameters",
    content:
      "Fast configuration with YAML file, including account settings, trading frequency, backtesting period, and risk management.",
    srcImage:
      "/image/config.png",
  },
  {
    title: "Update latest market data",
    content:
      "Retrieve latest price-volume data from a specified data source and store it in local database for seamless access and analysis.",
    srcImage:
      "/image/prefect.png",
  },
  {
    title: "Write strategy and perform backtest",
    content:
      "Define factor (expression) and calculate factor values for generating trading signals.",
    srcImage:
      "/image/config.png",
  },
  {
    title: "Trade live with real money",
    content:
      "Copy and paste the code generated by the Cuicui library into your project and enjoy modern, ready-to-use components.",
    srcImage:
      "/image/config.png",
  },
];

export function WorkflowImages() {
  const [featureOpen, setFeatureOpen] = useState(0);
  const [timer, setTimer] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setTimer((prev) => prev + 10);
    }, 10);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (timer > 10000) {
      setFeatureOpen((prev) => (prev + 1) % data.length);
      setTimer(0);
    }
  }, [timer]);

  return (
    <div className="container">
      <div className="md:mx-auto md:text-center md:max-w-7xl xl:max-w-none md:pt-6">
        <Heading>Automatic Quantitative Research Workflow</Heading>
        <Subheading>
          Build and deploy your own algorithmic trading strategy with only four steps.
        </Subheading>
      </div>
      <div className=" grid grid-cols-1 gap-8 md:grid-cols-2 pt-[40px] pb-[60px]">
        <div className="space-y-6 ">
          {data.map((item, index) => (
            <button
              className="w-full"
              key={item.title}
              onClick={() => {
                setFeatureOpen(index);
                setTimer(0);
              }}
              type="button"
            >
              <TextComponent
                content={item.content}
                isOpen={featureOpen === index}
                loadingWidthPercent={featureOpen === index ? timer / 100 : 0}
                number={index + 1}
                title={item.title}
              />
            </button>
          ))}
        </div>
        <div className="h-full">
          <div
            className={cn(
              "relative h-96 w-full overflow-hidden rounded-lg md:h-[500px]",
            )}
          >
            {data.map((item, index) => (
              <img
                alt={item.title}
                className={cn(
                  "absolute h-[500px] w-full transform-gpu rounded-lg object-cover transition-all duration-300",
                  featureOpen === index ? "scale-100" : "scale-70",
                  featureOpen > index ? "translate-y-full" : "",
                )}
                key={item.title}
                src={item.srcImage}
                style={{ zIndex: data.length - index, width: '600px', height: '600px' }}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
