import { Inter } from 'next/font/google';
import Head from 'next/head';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Frozen | 量化回测',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
        <title>Frozen | 量化回测框架</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
